### ISSUE TITLE
如何懒加载，如何提前加载？

### ISSUE THREAD

**Issue by zhuzhutai** [chenpengfei88/TabContainerView#2]
我想滑动到第二个页面时候才去初始化第2个页面的数据或者联网请求该怎么处理，这样的话直接四个Fragment是一次全部加载完的

**Comment by chenpengfei88** [comment]
tabContainerView.setOffscreenPageLimit(2);
可以设置ViewPager存在几个实例

要实现Fragment懒加载，要在Fragment中去操作

**Comment by zhuzhutai** [comment]
嗯，我试试用EventBus或者，在onHiddenChanged方法里面做些操作。这是第一次在githup项目里面留言。哈哈哈 加油

**Comment by chenpengfei88** [comment]
懒加载一般会用到Fragment的setUserVisibleHint这个方法
